# kubernetes/helm-charts/event-processor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-processor.fullname" . }}
  labels:
    {{- include "event-processor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "event-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "event-processor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "event-processor.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- toYaml .Values.env | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}